/**
 * FIS Error Code Mappings
 * Standard error codes for payment and token operations
 */

const ERROR_CODES = {
  // Validation Errors (DONEB-01XXX)
  AMOUNT_NEGATIVE: "DONEB-01001",
  AMOUNT_TOO_LOW: "DONEB-01002",
  CURRENCY_INVALID: "DONEB-02001",
  USERID_MISSING: "DONEB-03001",
  MISSING_BODY: "DONEB-04001",

  // System Errors (SYS-XXXXX)
  ACCOUNT_FROZEN: "SYS-00902",
  ELIGIBILITY_FAILED: "DONEB-35020",

  // Technical Errors (DONEB-8XXXX)
  SERVICE_UNAVAILABLE: "DONEB-80020",
  CONNECTION_FAILED: "DONEB-80021",
  TIMEOUT: "DONEB-80022",

  // Auth Errors (AUTH-XXX)
  TOKEN_EXPIRED: "AUTH-40101",
  TOKEN_INVALID: "AUTH-40102",
  UNAUTHORIZED: "AUTH-40103",

  // JOSE Errors
  JOSE_SIGNATURE_INVALID: "JOSE-SIG-001",
  JOSE_TOKEN_EXPIRED: "JOSE-EXP-001",

  // Generic
  INTERNAL_ERROR: "SYS-INTERNAL-500",
  UNKNOWN_ERROR: "SYS-UNKNOWN-001",
};

module.exports = { ERROR_CODES };
